version: '3.8'
services:
    db:
        image: postgres
        restart: always
        volumes: 
            - db:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: apollo
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        networks: 
            - apollo-api
    api:
        build: ./
        restart: always
        depends_on: 
            - db
        links:
            - db
        env_file: 
            - ./.env
        ports: 
            - 4000:4000
        networks: 
            - apollo-api

volumes:
    db:
    api:

networks:
    apollo-api:
        driver: bridge